-d C:\Users\User\Desktop\GOWIN\NCKUES_MMSoC_Class_UART_exp\impl\gwsynthesis\NCKUES_MMSoC_Class_UART_exp.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\User\Desktop\GOWIN\NCKUES_MMSoC_Class_UART_exp\src\uart_loopback.cst
-cfg C:\Users\User\Desktop\GOWIN\NCKUES_MMSoC_Class_UART_exp\impl\pnr\device.cfg
-sdc C:\Users\User\Desktop\GOWIN\NCKUES_MMSoC_Class_UART_exp\src\uart_loopback.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
